"""corretly model

Revision ID: 74cdd98cd99f
Revises: 1783241f2723
Create Date: 2025-01-27 10:48:45.158568

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '74cdd98cd99f'
down_revision: Union[str, None] = '1783241f2723'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('profile')
    op.drop_table('user_account')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_account',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('user_account_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('salt', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('hashed_password', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('username', sa.VARCHAR(length=30), autoincrement=False, nullable=False),
    sa.Column('fullname', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('email', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('key', sa.UUID(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='user_account_pkey'),
    sa.UniqueConstraint('email', name='user_account_email_key'),
    sa.UniqueConstraint('username', name='user_account_username_key'),
    postgresql_ignore_search_path=False
    )
    op.create_table('profile',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('work', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user_account.id'], name='profile_user_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='profile_pkey')
    )
    # ### end Alembic commands ###
