"""Описание изменений

Revision ID: 6b1c56fead52
Revises: c7ef212494f8
Create Date: 2025-01-27 12:10:50.114095

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6b1c56fead52'
down_revision: Union[str, None] = 'c7ef212494f8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_account', sa.Column('email2', sa.String(), nullable=False))
    op.create_unique_constraint(None, 'user_account', ['email2'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user_account', type_='unique')
    op.drop_column('user_account', 'email2')
    # ### end Alembic commands ###
