version: '3.8'

services:
  auth_service:
    build: ./auth_service
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
    restart: always
    volumes:
      - ./auth_service/:/auth_service/
    ports:
      - 8001:8000
    env_file:
      - ./auth_service/.env
    environment:
      - AUTH_SERVICE_HOST_URL=http://auth_service:8000/api/v1/auth
    depends_on:
      - auth_db
    networks:
      - backend

  auth_db:
    image: postgres:14
    volumes:
      - postgres_data_auth:/var/lib/postgresql/data/
    restart: always
    env_file:
      - ./auth_service/.env
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=yourpassword
      - POSTGRES_DB=test
    ports:
      - "5432:5432" # Открываем порт для подключения извне
    networks:
      - backend


  user_service:
    build: ./user_service
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
    restart: always
    volumes:
      - ./user_service/:/user_service/
    ports:
      - 8002:8000
    env_file:
      - ./user_service/.env
    environment:
      - USER_SERVICE_HOST_URL=http://user_service:8000/api/v1/user
    depends_on:
      - user_db
    networks:
      - backend

  user_db:
    image: postgres:14
    volumes:
      - postgres_data_user:/var/lib/postgresql/data/
    restart: always
    env_file:
      - ./user_service/.env
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=yourpassword
      - POSTGRES_DB=test
    ports:
      - "5433:5433" # Открываем порт для подключения извне
    networks:
      - backend


#  nginx:
#    image: nginx:latest
#    ports:
#      - "8080:8080"
#    volumes:
#      - ./nginx_config.conf:/etc/nginx/conf.d/default.conf
#    depends_on:
#      - user_service
#      - auth_service
volumes:
  postgres_data_user:
  postgres_data_auth:

networks:
  backend:
    driver: bridge
